### ISSUE TITLE
前端无法正常访问畅通的API地址

### ISSUE THREAD

**Issue by Well2333** [AegirTech/IberiaEye#2]
![image](https://user-images.githubusercontent.com/40534114/222183094-9af6e68f-7267-4c43-817c-a3f00c974380.png)
![image](https://user-images.githubusercontent.com/40534114/222183335-506fa9a9-9d2c-429a-8b22-6c8e5c56fd59.png)

如图，前端项目发起请求后没有正常的响应，但 Swagger UI 中一切正常。
由于本人不是很了解前端，在这里仅是猜测，前端项目是不是把需要使用 post 的方法用 get 发送出去了呢？

**Comment by fzf404** [comment]
已推送新版，旧版未适配新版前端。
